'use client';
import { useEffect, useMemo, useState } from 'react';
import { store } from '@/lib/storage';
import { coordinateCardio, recentTrainingLoad } from '@/lib/load-management';
import { ActivityDose, Assessment, CapabilityDomain, ReadinessInput, assessmentTrend, athleticPlan, capabilityMetrics, cardioEquivalentMinutes, cardioOptions, cardioPrescription, latestAssessment, minimumEffectiveOptions, progressionTracks, readinessDecision, readinessTrend, skillTrees, targetProgress, weeklyTargets } from '@/lib/whole-person';

function recent(d:ActivityDose){return Date.now()-new Date(d.completedAt).getTime()<=7*24*60*60*1000}

export function TodayWholePerson({strengthSessions}:{strengthSessions:number}){
  const [activity,setActivity]=useState<ActivityDose[]>([]); const [readiness,setReadiness]=useState<ReadinessInput>({sleep:'okay',fatigue:'moderate',soreness:'low',stress:'moderate'}); const [savedReadiness,setSavedReadiness]=useState<ReadinessInput|undefined>(); const [readinessRecords,setReadinessRecords]=useState<{recordedAt:string;input:ReadinessInput}[]>([]); const [minutes,setMinutes]=useState(20); const [effort,setEffort]=useState<'easy'|'moderate'|'hard'>('moderate'); const [skills,setSkills]=useState<Record<string,string>>({}); const [progressions,setProgressions]=useState<Record<string,string>>({}); const [assessments,setAssessments]=useState<Assessment[]>([]);
  useEffect(()=>{setActivity(store.loadActivity());const checks=store.loadReadiness();setReadinessRecords(checks);if(checks.length){setSavedReadiness(checks.at(-1)?.input);setReadiness(checks.at(-1)?.input||{})}setSkills(store.loadSkills());setProgressions(store.loadProgressions());setAssessments(store.loadAssessments())},[]);
  const cardioTarget=weeklyTargets.find(t=>t.domain==='cardio')?.minutes||150; const cardioMinutes=useMemo(()=>activity.filter(d=>d.domain==='cardio'&&recent(d)).reduce((s,d)=>s+cardioEquivalentMinutes(d.minutes||0,d.effort||'moderate'),0),[activity]); const quick=minimumEffectiveOptions(10,['mobility','core','bodyweight']); const decision=readinessDecision(savedReadiness||{}); const prescription=cardioPrescription(cardioMinutes,cardioTarget,30); const load=recentTrainingLoad(store.loadHistory()); const cardioChoices=coordinateCardio(cardioOptions(cardioMinutes,cardioTarget,decision.level,30),load,decision.level); const recoveryTrend=readinessTrend(readinessRecords); const athletic=athleticPlan(assessments,decision.level);
  function saveCheck(){const next=[...store.loadReadiness(),{recordedAt:new Date().toISOString(),input:readiness}].slice(-90);store.saveReadiness(next);setReadinessRecords(next);setSavedReadiness(readiness)}
  function logCardio(){const dose:ActivityDose={domain:'cardio',minutes,effort,sessionId:'manual-cardio',completedAt:new Date().toISOString()};const next=[...activity,dose];store.saveActivity(next);setActivity(next)}
  function logMicro(domain:CapabilityDomain,sessionMinutes:number,sessionId?:string){const dose:ActivityDose={domain,minutes:sessionMinutes,effort:'easy',sessionId,completedAt:new Date().toISOString()};const next=[...activity,dose];store.saveActivity(next);setActivity(next)}
  function setSkill(treeId:string,stepId:string){const next={...skills,[treeId]:stepId};store.saveSkills(next);setSkills(next)} function setProgression(trackId:string,levelId:string){const next={...progressions,[trackId]:levelId};store.saveProgressions(next);setProgressions(next)}
  return <><section className="card"><h3>Whole-person fitness</h3><div className="metrics"><span><b>Strength</b>{strengthSessions}/4 recent sessions</span><span><b>Cardio</b>{Math.round(cardioMinutes)}/{cardioTarget} equivalent min</span><span><b>Mobility</b>{activity.filter(d=>d.domain==='mobility'&&recent(d)).length} recent sessions</span><span><b>Body control</b>{Object.keys(skills).length} skills in progress</span></div><div className="coach-note"><b>Cardio next step</b><br/>{prescription.message}</div>{quick[0]&&<p className="muted">Short on time? {quick[0].name} takes about {quick[0].minutes} minutes.</p>}</section>
  <section className="card"><h3>Readiness check</h3><p className="muted">Recovery changes the plan; it does not create a medical diagnosis.</p><div className="metrics"><label><b>Sleep</b><select value={readiness.sleep||'okay'} onChange={e=>setReadiness({...readiness,sleep:e.target.value as ReadinessInput['sleep']})}><option value="poor">Poor</option><option value="okay">Okay</option><option value="good">Good</option></select></label><label><b>Fatigue</b><select value={readiness.fatigue||'moderate'} onChange={e=>setReadiness({...readiness,fatigue:e.target.value as ReadinessInput['fatigue']})}><option value="low">Low</option><option value="moderate">Moderate</option><option value="high">High</option></select></label><label><b>Soreness</b><select value={readiness.soreness||'low'} onChange={e=>setReadiness({...readiness,soreness:e.target.value as ReadinessInput['soreness']})}><option value="low">Low</option><option value="moderate">Moderate</option><option value="high">High</option></select></label><label><b>Stress</b><select value={readiness.stress||'moderate'} onChange={e=>setReadiness({...readiness,stress:e.target.value as ReadinessInput['stress']})}><option value="low">Low</option><option value="moderate">Moderate</option><option value="high">High</option></select></label></div><div className="quick-grid"><button onClick={()=>setReadiness({...readiness,illness:!readiness.illness})}>{readiness.illness?'Illness flagged':'Flag illness'}</button><button onClick={()=>setReadiness({...readiness,pain:!readiness.pain})}>{readiness.pain?'Pain flagged':'Flag pain'}</button><button className="primary" onClick={saveCheck}>Save check-in</button></div><div className="coach-note"><b>{decision.level==='normal'?'Normal training':decision.level==='reduced'?'Reduce optional volume':'Recovery-first'}</b><br/>{decision.reasons.join(' ')||'No major recovery constraints are currently recorded.'}</div><p className="muted"><b>7-day pattern:</b> {recoveryTrend.message}</p></section>
  <section className="card"><h3>Cardio</h3>{load.hoursSinceLower!==null&&load.hoursSinceLower<36&&<p className="coach-note">Recent lower-body work: {load.lowerSets} sets. Hard intervals are deferred when that workload is demanding.</p>}<div className="quick-grid">{cardioChoices.map(c=><button key={c.type} onClick={()=>{setMinutes(Math.max(1,c.minutes));setEffort(c.effort)}}><b>{c.name}</b><br/><small>{c.minutes} min · {c.effort}</small></button>)}</div>{cardioChoices.map(c=><p className="muted" key={c.type}>{c.description}</p>)}<div className="log-box"><label>Minutes<input type="number" min="1" max="240" value={minutes} onChange={e=>setMinutes(Math.max(1,Number(e.target.value)))}/></label><label>Effort<select value={effort} onChange={e=>setEffort(e.target.value as typeof effort)}><option value="easy">Easy</option><option value="moderate">Moderate</option><option value="hard">Hard</option></select></label><button className="primary" onClick={logCardio}>Log cardio</button></div></section>
  <section className="card"><h3>Athleticism</h3>{athletic.map(p=><div className="history" key={p.domain}><b>{p.name}</b><span>{p.domain}</span><small>{p.items.join(' · ')} · {p.reason}</small><button className="link" onClick={()=>logMicro(p.domain,10,`athletic:${p.domain}`)}>Mark 10 min done</button></div>)}</section>
  <section className="card"><h3>Core + mobility progression</h3>{progressionTracks.map(track=>{const current=track.levels.find(l=>l.id===progressions[track.id])||track.levels[0];return <div key={track.id}><b>{track.name}</b><p className="muted">{current.name}: {current.target}</p><small>{current.items.join(' · ')}</small><div className="quick-grid">{track.levels.map(l=><button key={l.id} className={current.id===l.id?'active':''} onClick={()=>setProgression(track.id,l.id)}>{l.name}</button>)}<button className="primary" onClick={()=>logMicro(track.domain,8,`${track.id}:${current.id}`)}>Complete 8 min</button></div></div>})}</section>
  <section className="card"><h3>Quick whole-person work</h3>{quick.map(s=><div className="history" key={s.id}><b>{s.name}</b><span>{s.minutes} min</span><small>{s.items.join(' · ')}</small><button className="link" onClick={()=>logMicro(s.domain,s.minutes,s.id)}>Mark done</button></div>)}</section>
  <section className="card"><h3>Bodyweight skills</h3>{skillTrees.map(tree=><div key={tree.id}><b>{tree.name}</b><div className="quick-grid">{tree.steps.map(step=><button key={step.id} className={skills[tree.id]===step.id?'active':''} onClick={()=>setSkill(tree.id,step.id)}>{step.name}</button>)}</div></div>)}</section></>;
}

export function CapabilityPanel(){const [activity,setActivity]=useState<ActivityDose[]>([]);const [assessments,setAssessments]=useState<Assessment[]>([]);const [metricId,setMetricId]=useState('pullups');const [value,setValue]=useState(0);useEffect(()=>{setActivity(store.loadActivity());setAssessments(store.loadAssessments())},[]);const cardioTarget=weeklyTargets.find(t=>t.domain==='cardio')?.minutes||150;const cardio=activity.filter(d=>d.domain==='cardio'&&recent(d)).reduce((s,d)=>s+cardioEquivalentMinutes(d.minutes||0,d.effort||'moderate'),0);function record(){const next=[...assessments,{metricId,value,recordedAt:new Date().toISOString()}];store.saveAssessments(next);setAssessments(next)}return <section className="card"><h2>Capability map</h2><p className="muted">Domains stay measurable on their own; there is no universal medical health score.</p><div className="metrics"><span><b>Cardio target</b>{Math.round(targetProgress(cardio,cardioTarget)*100)}%</span><span><b>Recorded domains</b>{new Set(activity.map(a=>a.domain)).size}</span></div><div className="log-box"><label>Assessment<select value={metricId} onChange={e=>setMetricId(e.target.value)}>{capabilityMetrics.filter(m=>['pullups','dead-hang','ankle-mobility','single-leg-balance','jump'].includes(m.id)).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Value<input type="number" value={value} onChange={e=>setValue(Number(e.target.value))}/></label><button className="primary" onClick={record}>Record test</button></div>{capabilityMetrics.map(m=>{const latest=latestAssessment(assessments,m.id);const trend=assessmentTrend(assessments,m.id);return <div className="history" key={m.id}><b>{m.name}</b><span>{latest?`${latest.value} ${m.unit}`:m.unit}</span><small>{m.domain} · {m.description}{trend!==null?` · change ${trend>0?'+':''}${trend}`:''}</small></div>})}</section>}
