import { Exercise } from './domain';
import { defineExercise } from './exercise-definition';

export const upperPullExercises: Exercise[] = [
  defineExercise({ id: 'row', name: 'Barbell Row', movement: 'horizontal-pull', equipment: ['barbell'], priority: 'primary', repRange: [6, 10], metadata: { primaryMuscles: ['upper back', 'lats'], secondaryMuscles: ['biceps', 'spinal erectors'], stability: 'high', fatigueCost: 'moderate', skillLevel: 'intermediate', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'cable-row', name: 'Cable Row', movement: 'horizontal-pull', equipment: ['cable'], priority: 'primary', repRange: [8, 12], metadata: { primaryMuscles: ['upper back', 'lats'], secondaryMuscles: ['biceps'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),
  defineExercise({ id: 'machine-row', name: 'Machine Row', movement: 'horizontal-pull', equipment: ['machine'], priority: 'primary', repRange: [8, 12], metadata: { primaryMuscles: ['upper back', 'lats'], secondaryMuscles: ['biceps'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),
  defineExercise({ id: 'dumbbell-row', name: 'Dumbbell Row', movement: 'horizontal-pull', equipment: ['dumbbell'], priority: 'primary', repRange: [8, 12], metadata: { primaryMuscles: ['upper back', 'lats'], secondaryMuscles: ['biceps'], stability: 'moderate', fatigueCost: 'moderate', skillLevel: 'beginner', unilateral: true, loadType: 'external' } }),
  defineExercise({ id: 'inverted-row', name: 'Inverted Row', movement: 'horizontal-pull', equipment: ['bodyweight', 'rack'], priority: 'secondary', repRange: [6, 15], metadata: { primaryMuscles: ['upper back', 'lats'], secondaryMuscles: ['biceps'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'bodyweight' } }),
  defineExercise({ id: 'pulldown', name: 'Cable Lat Pulldown', movement: 'vertical-pull', equipment: ['cable'], priority: 'secondary', repRange: [8, 12], metadata: { primaryMuscles: ['lats'], secondaryMuscles: ['biceps', 'upper back'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),
  defineExercise({ id: 'pullup', name: 'Pull-Up', movement: 'vertical-pull', equipment: ['bodyweight', 'pullup-bar'], priority: 'secondary', repRange: [5, 10], metadata: { primaryMuscles: ['lats'], secondaryMuscles: ['biceps', 'upper back'], stability: 'moderate', fatigueCost: 'moderate', skillLevel: 'intermediate', unilateral: false, loadType: 'bodyweight' } }),
  defineExercise({ id: 'chinup', name: 'Chin-Up', movement: 'vertical-pull', equipment: ['bodyweight', 'pullup-bar'], priority: 'secondary', repRange: [5, 10], metadata: { primaryMuscles: ['lats', 'biceps'], secondaryMuscles: ['upper back'], stability: 'moderate', fatigueCost: 'moderate', skillLevel: 'intermediate', unilateral: false, loadType: 'bodyweight' } }),
  defineExercise({ id: 'assisted-pullup', name: 'Assisted Pull-Up Machine', movement: 'vertical-pull', equipment: ['machine'], priority: 'secondary', repRange: [6, 12], metadata: { primaryMuscles: ['lats'], secondaryMuscles: ['biceps', 'upper back'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),
  defineExercise({ id: 'dumbbell-pullover', name: 'Dumbbell Pullover', movement: 'vertical-pull', equipment: ['dumbbell', 'bench'], priority: 'accessory', repRange: [10, 15], metadata: { primaryMuscles: ['lats'], secondaryMuscles: ['chest'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'dead-hang', name: 'Dead Hang', movement: 'vertical-pull', equipment: ['bodyweight', 'pullup-bar'], priority: 'accessory', repRange: [20, 60], metadata: { primaryMuscles: ['grip'], secondaryMuscles: ['shoulders', 'lats'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'bodyweight' } }),
  defineExercise({ id: 'curl', name: 'Cable Curl', movement: 'biceps', equipment: ['cable'], priority: 'accessory', repRange: [10, 15], metadata: { primaryMuscles: ['biceps'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),
  defineExercise({ id: 'db-curl', name: 'Dumbbell Curl', movement: 'biceps', equipment: ['dumbbell'], priority: 'accessory', repRange: [8, 15], metadata: { primaryMuscles: ['biceps'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: true, loadType: 'external' } }),
  defineExercise({ id: 'barbell-curl', name: 'Barbell Curl', movement: 'biceps', equipment: ['barbell'], priority: 'accessory', repRange: [8, 15], metadata: { primaryMuscles: ['biceps'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'external' } }),

];
