import { Exercise } from './domain';
import { defineExercise } from './exercise-definition';

export const upperPushExercises: Exercise[] = [
  defineExercise({ id: 'bench', name: 'Barbell Bench Press', movement: 'horizontal-push', equipment: ['barbell', 'bench', 'rack'], priority: 'primary', repRange: [5, 8], metadata: { primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'front delts'], stability: 'high', fatigueCost: 'moderate', skillLevel: 'intermediate', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'incline', name: 'Incline Barbell Press', movement: 'horizontal-push', equipment: ['barbell', 'bench', 'rack'], priority: 'primary', repRange: [6, 10], metadata: { primaryMuscles: ['upper chest'], secondaryMuscles: ['triceps', 'front delts'], stability: 'high', fatigueCost: 'moderate', skillLevel: 'intermediate', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'dumbbell-bench', name: 'Dumbbell Bench Press', movement: 'horizontal-push', equipment: ['dumbbell', 'bench'], priority: 'primary', repRange: [6, 10], metadata: { primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'front delts'], stability: 'high', fatigueCost: 'moderate', skillLevel: 'intermediate', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'machine-chest', name: 'Chest Press Machine', movement: 'horizontal-push', equipment: ['machine'], priority: 'primary', repRange: [6, 10], metadata: { primaryMuscles: ['chest'], secondaryMuscles: ['triceps'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),
  defineExercise({ id: 'pushup', name: 'Push-Up', movement: 'horizontal-push', equipment: ['bodyweight'], priority: 'secondary', repRange: [8, 20], metadata: { primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'front delts'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'bodyweight' } }),
  defineExercise({ id: 'dip', name: 'Dip', movement: 'horizontal-push', equipment: ['bodyweight', 'dip-station'], priority: 'secondary', repRange: [5, 12], metadata: { primaryMuscles: ['chest', 'triceps'], secondaryMuscles: ['front delts'], stability: 'moderate', fatigueCost: 'moderate', skillLevel: 'intermediate', unilateral: false, loadType: 'bodyweight' } }),
  defineExercise({ id: 'cable-fly', name: 'Cable Fly', movement: 'horizontal-push', equipment: ['cable'], priority: 'accessory', repRange: [10, 15], metadata: { primaryMuscles: ['chest'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),
  defineExercise({ id: 'ohp', name: 'Barbell Overhead Press', movement: 'vertical-push', equipment: ['barbell', 'rack'], priority: 'secondary', repRange: [6, 10], metadata: { primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps', 'upper chest'], stability: 'high', fatigueCost: 'moderate', skillLevel: 'intermediate', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'dumbbell-ohp', name: 'Dumbbell Shoulder Press', movement: 'vertical-push', equipment: ['dumbbell'], priority: 'secondary', repRange: [8, 12], metadata: { primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps'], stability: 'moderate', fatigueCost: 'moderate', skillLevel: 'beginner', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'machine-ohp', name: 'Shoulder Press Machine', movement: 'vertical-push', equipment: ['machine'], priority: 'secondary', repRange: [8, 12], metadata: { primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),
  defineExercise({ id: 'pike-pushup', name: 'Pike Push-Up', movement: 'vertical-push', equipment: ['bodyweight'], priority: 'secondary', repRange: [6, 15], metadata: { primaryMuscles: ['shoulders'], secondaryMuscles: ['triceps'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'intermediate', unilateral: false, loadType: 'bodyweight' } }),
  defineExercise({ id: 'pushdown', name: 'Cable Triceps Pushdown', movement: 'triceps', equipment: ['cable'], priority: 'accessory', repRange: [10, 15], metadata: { primaryMuscles: ['triceps'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),
  defineExercise({ id: 'overhead-triceps', name: 'Overhead Cable Triceps Extension', movement: 'triceps', equipment: ['cable'], priority: 'accessory', repRange: [10, 15], metadata: { primaryMuscles: ['triceps'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),
  defineExercise({ id: 'db-triceps', name: 'Dumbbell Triceps Extension', movement: 'triceps', equipment: ['dumbbell'], priority: 'accessory', repRange: [10, 15], metadata: { primaryMuscles: ['triceps'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'skull-crusher', name: 'Barbell Triceps Extension', movement: 'triceps', equipment: ['barbell', 'bench'], priority: 'accessory', repRange: [8, 15], metadata: { primaryMuscles: ['triceps'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'intermediate', unilateral: false, loadType: 'external' } }),

  defineExercise({ id: 'pallof', name: 'Pallof Press', movement: 'core', equipment: ['cable'], priority: 'accessory', repRange: [8, 12], metadata: { primaryMuscles: ['trunk'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: true, loadType: 'machine' } }),
  defineExercise({ id: 'plank', name: 'Plank', movement: 'core', equipment: ['bodyweight'], priority: 'accessory', repRange: [30, 60], metadata: { primaryMuscles: ['trunk'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'bodyweight' } }),
  defineExercise({ id: 'side-plank', name: 'Side Plank', movement: 'core', equipment: ['bodyweight'], priority: 'accessory', repRange: [20, 45], metadata: { primaryMuscles: ['trunk'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: true, loadType: 'bodyweight' } }),
  defineExercise({ id: 'reverse-crunch', name: 'Reverse Crunch', movement: 'core', equipment: ['bodyweight'], priority: 'accessory', repRange: [8, 15], metadata: { primaryMuscles: ['trunk'], secondaryMuscles: ['hip flexors'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'bodyweight' } }),
  defineExercise({ id: 'hanging-knee-raise', name: 'Hanging Knee Raise', movement: 'core', equipment: ['bodyweight', 'pullup-bar'], priority: 'accessory', repRange: [6, 15], metadata: { primaryMuscles: ['trunk'], secondaryMuscles: ['hip flexors', 'grip'], stability: 'moderate', fatigueCost: 'moderate', skillLevel: 'intermediate', unilateral: false, loadType: 'bodyweight' } }),
];
