import { Exercise } from './domain';
import { defineExercise } from './exercise-definition';

export const lowerExercises: Exercise[] = [
  defineExercise({ id: 'squat', name: 'Barbell Back Squat', movement: 'squat', equipment: ['barbell', 'rack'], priority: 'primary', repRange: [5, 8], metadata: { primaryMuscles: ['quadriceps', 'glutes'], secondaryMuscles: ['adductors', 'trunk'], stability: 'high', fatigueCost: 'high', skillLevel: 'intermediate', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'front-squat', name: 'Front Squat', movement: 'squat', equipment: ['barbell', 'rack'], priority: 'primary', repRange: [5, 10], metadata: { primaryMuscles: ['quadriceps', 'glutes'], secondaryMuscles: ['upper back', 'trunk'], stability: 'high', fatigueCost: 'high', skillLevel: 'advanced', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'goblet-squat', name: 'Goblet Squat', movement: 'squat', equipment: ['dumbbell'], priority: 'primary', repRange: [8, 15], metadata: { primaryMuscles: ['quadriceps', 'glutes'], secondaryMuscles: ['trunk'], stability: 'moderate', fatigueCost: 'moderate', skillLevel: 'beginner', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'leg-press', name: 'Leg Press', movement: 'squat', equipment: ['machine'], priority: 'primary', repRange: [8, 15], metadata: { primaryMuscles: ['quadriceps', 'glutes'], stability: 'low', fatigueCost: 'moderate', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),
  defineExercise({ id: 'bodyweight-squat', name: 'Tempo Bodyweight Squat', movement: 'squat', equipment: ['bodyweight'], priority: 'secondary', repRange: [12, 25], metadata: { primaryMuscles: ['quadriceps', 'glutes'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'bodyweight' } }),

  defineExercise({ id: 'rdl', name: 'Romanian Deadlift', movement: 'hinge', equipment: ['barbell'], priority: 'primary', repRange: [6, 10], metadata: { primaryMuscles: ['hamstrings', 'glutes'], secondaryMuscles: ['spinal erectors', 'grip'], stability: 'high', fatigueCost: 'high', skillLevel: 'intermediate', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'db-rdl', name: 'Dumbbell Romanian Deadlift', movement: 'hinge', equipment: ['dumbbell'], priority: 'primary', repRange: [8, 12], metadata: { primaryMuscles: ['hamstrings', 'glutes'], secondaryMuscles: ['grip'], stability: 'moderate', fatigueCost: 'moderate', skillLevel: 'beginner', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'good-morning', name: 'Barbell Good Morning', movement: 'hinge', equipment: ['barbell', 'rack'], priority: 'secondary', repRange: [8, 12], metadata: { primaryMuscles: ['hamstrings', 'glutes'], secondaryMuscles: ['spinal erectors'], stability: 'high', fatigueCost: 'moderate', skillLevel: 'advanced', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'cable-pull-through', name: 'Cable Pull-Through', movement: 'hinge', equipment: ['cable'], priority: 'secondary', repRange: [10, 15], metadata: { primaryMuscles: ['glutes', 'hamstrings'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),
  defineExercise({ id: 'single-leg-rdl', name: 'Single-Leg Bodyweight RDL', movement: 'hinge', equipment: ['bodyweight'], priority: 'secondary', repRange: [8, 15], metadata: { primaryMuscles: ['hamstrings', 'glutes'], secondaryMuscles: ['balance'], stability: 'high', fatigueCost: 'low', skillLevel: 'intermediate', unilateral: true, loadType: 'bodyweight' } }),

  defineExercise({ id: 'split-squat', name: 'Bulgarian Split Squat', movement: 'single-leg', equipment: ['bench', 'bodyweight'], priority: 'secondary', repRange: [8, 12], metadata: { primaryMuscles: ['quadriceps', 'glutes'], secondaryMuscles: ['adductors'], stability: 'high', fatigueCost: 'moderate', skillLevel: 'intermediate', unilateral: true, loadType: 'bodyweight' } }),
  defineExercise({ id: 'reverse-lunge', name: 'Reverse Lunge', movement: 'single-leg', equipment: ['bodyweight'], priority: 'secondary', repRange: [8, 15], metadata: { primaryMuscles: ['quadriceps', 'glutes'], secondaryMuscles: ['adductors'], stability: 'moderate', fatigueCost: 'moderate', skillLevel: 'beginner', unilateral: true, loadType: 'bodyweight' } }),
  defineExercise({ id: 'db-lunge', name: 'Dumbbell Reverse Lunge', movement: 'single-leg', equipment: ['dumbbell'], priority: 'secondary', repRange: [8, 12], metadata: { primaryMuscles: ['quadriceps', 'glutes'], secondaryMuscles: ['adductors', 'grip'], stability: 'high', fatigueCost: 'moderate', skillLevel: 'intermediate', unilateral: true, loadType: 'external' } }),
  defineExercise({ id: 'step-up', name: 'Step-Up', movement: 'single-leg', equipment: ['bench', 'bodyweight'], priority: 'secondary', repRange: [8, 15], metadata: { primaryMuscles: ['quadriceps', 'glutes'], stability: 'moderate', fatigueCost: 'moderate', skillLevel: 'beginner', unilateral: true, loadType: 'bodyweight' } }),

  defineExercise({ id: 'hip-thrust', name: 'Barbell Hip Thrust', movement: 'glute', equipment: ['barbell', 'bench'], priority: 'secondary', repRange: [8, 12], metadata: { primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings'], stability: 'moderate', fatigueCost: 'moderate', skillLevel: 'beginner', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'db-hip-thrust', name: 'Dumbbell Hip Thrust', movement: 'glute', equipment: ['dumbbell', 'bench'], priority: 'secondary', repRange: [10, 15], metadata: { primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'glute-bridge', name: 'Glute Bridge', movement: 'glute', equipment: ['bodyweight'], priority: 'secondary', repRange: [12, 20], metadata: { primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'bodyweight' } }),

  defineExercise({ id: 'calf', name: 'Standing Calf Raise', movement: 'calf', equipment: ['bodyweight'], priority: 'accessory', repRange: [12, 20], metadata: { primaryMuscles: ['calves'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'bodyweight' } }),
  defineExercise({ id: 'db-calf', name: 'Dumbbell Calf Raise', movement: 'calf', equipment: ['dumbbell'], priority: 'accessory', repRange: [10, 20], metadata: { primaryMuscles: ['calves'], stability: 'moderate', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'external' } }),
  defineExercise({ id: 'machine-calf', name: 'Calf Raise Machine', movement: 'calf', equipment: ['machine'], priority: 'accessory', repRange: [10, 20], metadata: { primaryMuscles: ['calves'], stability: 'low', fatigueCost: 'low', skillLevel: 'beginner', unilateral: false, loadType: 'machine' } }),

];
